# This file is *NOT* reloaded automatically when you use 'jekyll serve'.
# If you change this file, please restart the server process.
include: ['_pages']

title: Paris Call
baseurl: ""
url: https://ambanum.github.io

supporter_categories: [ private_sector, civil_society, state ]
available_languages: [ en, fr ]

collections:
  supporters_en:
    output: true
    permalink: en/supporter/:path/
  supporters_fr:
    output: true
    permalink: fr/supporter/:path/
  events:

defaults:
  - scope:
      path: _pages
    values:
      layout: page
  - scope:
      path: _pages/en
    values:
      lang: en
  - scope:
      path: _pages/fr
    values:
      lang: fr
  - scope:
      path: _supporters_fr
    values:
      layout: supporter
      lang: fr
  - scope:
      path: _supporters_en
    values:
      layout: supporter
      lang: en

sass:
  style: compact # possible values: nested expanded compact compressed

exclude:
  - vendor
  - README.md
  - .circleci
  - .gitignore
  - .ruby_version
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-environment-variables
