# This file is *NOT* reloaded automatically when you use 'jekyll serve'.
# If you change this file, please restart the server process.
include: ['_pages']

baseurl: ""
url: https://pariscall.international/

supporter_categories: [ private_sector, civil_society, state ]
available_languages: [ en, fr ]
typeform_urls:
  support:
    en: https://ambanum.typeform.com/to/qjm1oJ
    fr: https://ambanum.typeform.com/to/Y5eTGr
  event:
    en: https://ambanum.typeform.com/to/Gqi5uB
    fr: https://ambanum.typeform.com/to/OYvfQd

collections:
  events:
    output: true
  supporters_en:
  supporters_fr:

defaults:
  - scope:
      path: _events
    values:
      layout: event
      permalink: events/:name.ics
  - scope:
      path: _pages
    values:
      layout: page
  - scope:
      path: _pages/en
    values:
      lang: en
  - scope:
      path: _pages/fr
    values:
      lang: fr
  - scope:
      path: _pages/en/by-email
    values:
      layout: by-email
  - scope:
      path: _pages/fr/by-email
    values:
      layout: by-email

sass:
  style: compact # possible values: nested expanded compact compressed

exclude:
  - vendor
  - README.md
  - .circleci
  - .gitignore
  - .ruby_version
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-environment-variables
