# This file is *NOT* reloaded automatically when you use 'jekyll serve'.
# If you change this file, please restart the server process.
include: ['_pages']

title: Paris Call
baseurl: ""
url: https://ambanum.github.io

supporter_categories: [ "private_sector", "civil_society", "state" ]
available_languages: [ "en", "fr" ]

collections:
  supporters:
  events:

defaults:
  - scope:
      path: _supporters
    values:
      layout: supporter
      bodyClass: supporter-page

sass:
  style: compact # possible values: nested expanded compact compressed

exclude:
  - vendor
  - README.md
  - .circleci
  - .gitignore
  - .ruby_version
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-environment-variables
