# This file is *NOT* reloaded automatically when you use 'jekyll serve'.
# If you change this file, please restart the server process.

title: Paris Call
baseurl: /ParisCall
url: https://ambanum.github.io

supporter_categories: [ "private_sector", "civil_society", "state" ]

collections:
  supporters:
    output: true
    permalink: /supporter/:path/

defaults:
  - scope:
      path: _supporters
    values:
      layout: supporter

sass:
  style: compact # possible values: nested expanded compact compressed

exclude:
  - .circleci
  - .gitignore
  - .ruby_version
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-environment-variables
